baseURL = "https://keyb1nd.com"
theme   = "sk3"
title   = "Keyb1nd"

DefaultContentLanguage = "en"
enableGitInfo          = false
enableInlineShortcodes = true
languageCode           = "en"
paginate               = 50
relativeURLs           = true

[Params]
mainSections = "posts"
commandSection = "commands"
# pagewidth    = "1200px"
# startdate    = "2012-12-02"
favicon        = "/favicon.ico"
listlastmod    = true
openToc        = true
pageinfobox    = true
subtitle       = ""
svg_ext        = true
user_canonical = false

# Fill in following if using opengraph / twitter card
description = ""
opengraph   = true
title       = "Keyb1nd"
twitercards = true

[Params.card]
date    = true
summary = true
# width = "32%"

# [Params.color]
bg     = "white"
border = "white"
link   = "red"
text   = "white"

[Params.sociallink]
facebook       = "keyb1nd"
instagram      = "keyb1nd_"
reddit         = "keyb1nd"
twitter        = "keyb1nd"
youtubechannel = "UCArOyjiZlE5tp2bjdnsSVtA"

[Params.socialshare]
facebook  = true
linkedin  = true
pinterest = true
reddit    = true
telegram  = true
twitter   = true
vk        = false

[markup]
defaultMarkdownHandler = "goldmark"

[markup.highlight]
codeFences         = true
guessSyntax        = false
hl_Lines           = ""
lineNoStart        = 1
lineNos            = true
lineNumbersInTable = true
noClasses          = true
style              = "fruity"
tabWidth           = 4

[markup.tableOfContents]
endLevel   = 6
ordered    = false
startLevel = 1

[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote       = true
linkify        = true
strikethrough  = true
table          = true
taskList       = true
typographer    = true
[markup.goldmark.parser]
attribute         = true
autoHeadingID     = true
autoHeadingIDType = "github"
[markup.goldmark.renderer]
hardWraps = false
unsafe    = true
xhtml     = false
